### ISSUE TITLE
New attributes on elements always on a new line

### ISSUE THREAD

**Issue by gforcada** [collective/zpretty#2]
One of the main goals of zpretty is to make diff's easier, for that IMHO attributes should always be on a new line rather than aligned with the element, this way if you end up changing your mind and replacing a div for a span you only have two line diff's rather than all attributes.

**Comment by ale-rt** [comment]
This was one of the things I did not really had a strong opinion.

What lead me to the actual implementation is:

1. Three lines just for `<div class="something"></div>` seemed a bit too much and if you change the element name it is actually a one line diff
2. you hardly change the element tag and in that case ignoring whitespaces results in a tool line diff.  (which is easy in diff tools and even on github/gitlab/bitbucket if you append ?w=1 to the diff url)

So I thought that adding a newlines only after the first attribute would be a good compromise.

Note that you often want to use `git diff -w` when dealing with this kind of files. Otherwise you should stop to indent your code at all.

Did I convinced you.

**Comment by gforcada** [comment]
For this specific case, yes, one line is enough, but as soon as you have more than one attribute or that single attribute is already quite long it's not that readable either (i.e. pep8 80chars limit)

**Comment by gforcada** [comment]
So I would keep everything in one line if there is just one attribute or none and multi-line as soon as there is two attributes.

**Comment by ale-rt** [comment]
Ok, so maybe this will be fine once #2 is implemented.

**Comment by gforcada** [comment]
Yup, let's close this one then.
