### ISSUE TITLE
Add globbing support

### ISSUE THREAD

**Issue by rnixx** [collective/zpretty#96]
Would be great if this tool supports globbing patterns for input

**Comment by gforcada** [comment]
I usually look at that myself on tools I use (`flake8`, `black`, `isort`...) but then I stumbled upon `pyupgrade` that refuses to do that, see https://github.com/asottile/pyupgrade/issues/40 for the rationale.

Since then (a few weeks ago 😄 ) and specially for running these tools with `tox` (see [meta configuration](https://github.com/plone/meta/blob/master/config/default/tox.ini.j2#L36-L38)) I used instead `git ls-files` that has pattern matching and you can then pipe that to the tool 🍀 

Side note: we will probably integrate `zpretty` on [plone/meta](https://github.com/plone/meta/issues/33) as well 🎉

**Comment by ale-rt** [comment]
I strongly suggest to use a [pre-commit file](https://github.com/syslabcom/recensio.plone/blob/d6129fe46973fb268acbff80cf841878c731a800/.pre-commit-config.yaml) for the task of linting the files in a package.

**Comment by ale-rt** [comment]
I will probably try to mimic the way black does with the `--include` and the `--exclude` parameters

**Comment by jensens** [comment]
with pre-commit it is:
```
-   repo: https://github.com/collective/zpretty
    rev: 3.0.3
    hooks:
    -   id: zpretty
        exclude: plone/app/content/browser/contents/templates/properties.pt
```

**Comment by ale-rt** [comment]
For the moment, I am testing this with a pre-released version:

- https://pypi.org/project/zpretty/3.1.0a1/
